name: finutss
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.37+38

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.1
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  get: ^4.1.4
  http: ^0.13.4
  # flutter_mapbox_navigation: ^0.0.24
  location: ^4.4.0
  percent_indicator: ^4.2.2
  flutter_staggered_grid_view: ^0.6.1
  animated_bottom_navigation_bar: ^1.1.0
  carousel_slider: ^4.0.0
  flutter_switch: ^0.3.2
  flutter_screenutil: ^5.2.0
  community_material_icon: ^5.9.55
  graphql_flutter: ^5.0.0
  shared_preferences: ^2.0.13
  permission_handler: any
  webview_flutter_plus: ^0.3.0+2
  intl: ^0.17.0
  flutter_blue: ^0.8.0
  measure_size: ^4.0.0
  image_picker: ^0.8.5+3
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.10.0
  sendbird_sdk: ^3.1.7
  firebase_messaging: ^14.1.0
#  firebase_core_web: 1.5.4
  flutter_local_notifications: ^9.3.1
  wakelock: ^0.6.2
  flutter_html: any
  video_player_web: ^2.0.7
  kakao_flutter_sdk: ^1.2.0
  url_launcher: ^6.0.20
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  cached_network_image: ^3.2.3
  fluttertoast: ^8.0.9
  share_plus: ^6.3.0
  screenshot: ^1.2.3
  path_provider: ^2.0.11
  #syncfusion_flutter_gauges: ^19.1.54
  pedometer: ^3.0.0
  geolocator: ^9.0.0
  #mapbox_gl: ^0.15.0
  flutter_svg: ^1.1.6
  sleek_circular_slider: ^2.0.1
  tab_indicator_styler: ^2.0.0
  chips_choice_null_safety: ^2.0.6
  clipboard: ^0.1.3
  table_calendar: ^3.0.7
  auto_size_text: ^3.0.0
  photo_view: ^0.14.0
  video_thumbnail: ^0.5.0
  video_player: ^2.4.7
  voice_message_package: ^0.0.61
  csslib: 0.17.0
  syncfusion_flutter_sliders:
  http_interceptor: ^1.0.2
  another_flushbar: ^1.12.29
  loading_indicator: ^3.0.2
  firebase_core: ^2.2.0
  localization: ^2.1.0
  scrollable_list_tab_scroller: ^1.1.0
  volume_control: ^0.1.5
  uni_links: ^0.5.1
  shimmer: ^2.0.0
  volume:
    git:
      url: https://github.com/ashishbeck/Volume_Flutter
  html_character_entities: ^1.0.0+1
  flick_video_player: ^0.5.0
  flutter_pdfview: 1.2.9
  sprintf: ^7.0.0
  preload_page_view: ^0.1.6
  connectivity_plus: ^1.0.1
  horizontal_picker: ^1.2.0
  pod_player:
#    path: ./pod_player-0.1.2
  flutter_inapp_purchase:
    path: ./flutter_inapp_purchase-5.4.1
  socket_io_client: ^2.0.1
  web_socket_channel: 2.2.0
  youtube_player_flutter: ^8.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - new_assets/images/sensorSlider/
    - new_assets/icon/
    - new_assets/images/
    - new_assets/langs/
    - new_assets/webview/
    - new_assets/webview/img/
    - new_assets/webview/js/
    - new_assets/webview/css/
    - pubspec.yaml
    # - assets/images/followers.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 100
        - asset: fonts/Montserrat-Light.ttf
          weight: 200
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Thin.ttf


    - family: MontserratItalic
      fonts:
        - asset: fonts/Montserrat_BoldItalic.otf
          weight: 800
        - asset: fonts/Montserrat_SemiBoldItalic.otf
          weight: 600
        - asset: fonts/Montserrat_ExtraBoldItalic.otf
          weight: 700
        - asset: fonts/Montserrat_BlackItalic.otf
          weight: 900
        - asset: fonts/Montserrat_MediumItalic.otf
          weight: 500
        - asset: fonts/Montserrat_LightItalic.otf
          weight: 400


    - family: jura
      fonts:
        - asset: fonts/JuraSemiBold.ttf
          weight: 800
        - asset: fonts/JuraMedium.otf
          weight: 600


  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"